steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sinuous-tuner-303004/demo-note-apps', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sinuous-tuner-303004/demo-note-apps']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'beta', 'run', 'deploy', 'demo-note-apps', 
    '--image', 'gcr.io/sinuous-tuner-303004/demo-note-apps',
    '--region', 'asia-southeast2',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--add-cloudsql-instances', 'sinuous-tuner-303004:asia-southeast2:jejual-digipreneur-service',
    '--project', 'sinuous-tuner-303004',
    '--set-env-vars',
    'NODE_ENV=production,DB_NAME=note,DB_DIALECT=mysql',
    '--set-secrets',
    'DB_USER=db-user:latest,DB_PASSWORD=db-pass:latest,DB_SOCKET_PATH=db-connection-name:latest'
  ]
images:
- gcr.io/sinuous-tuner-303004/demo-note-apps